
// LOCAL BACK SERVER
const BACK_URL = process.env.NEXT_PUBLIC_BACK_SERVER as string

// RECRUIT JSON SERVER
const RECRUIT_ARTICLES_URL = process.env.NEXT_PUBLIC_JSON_SERVER_XXX as string // 4001
const RECRUIT_COMMENTS_URL = process.env.NEXT_PUBLIC_JSON_SERVER_YYY as string // 4002

// GYM JSON SERVER
const GYM_ARTICLES_URL = process.env.NEXT_PUBLIC_JSON_SERVER_GYMARTICLES as string // 5001
const GYM_REVIEWS_URL  = process.env.NEXT_PUBLIC_JSON_SERVER_GYMREVIEWS  as string // 5002
const GYM_COMMENTS_URL = process.env.NEXT_PUBLIC_JSON_SERVER_GYMCOMMENTS as string // 5003

// TEST JSON SERVER
const TEST_URL = process.env.NEXT_PUBLIC_JSON_SERVER_TEST as string

// http://localhost:


export {
  BACK_URL,
  RECRUIT_ARTICLES_URL,
  RECRUIT_COMMENTS_URL,
  GYM_ARTICLES_URL, 
  GYM_REVIEWS_URL, 
  GYM_COMMENTS_URL, 
  TEST_URL,
}